# Generated by Django 6.0.1 on 2026-02-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(choices=[('KOSHI', 'Koshi'), ('MADHESH', 'Madhesh'), ('BAGMATI', 'Bagmati'), ('GANDAKI', 'Gandaki'), ('LUMBINI', 'Lumbini'), ('KARNALI', 'Karnali'), ('SUDURPASHCHIM', 'Sudurpashchim'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
