# Generated by Django 6.0.2 on 2026-02-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number_customuser_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
