# Generated by Django 6.0.1 on 2026-02-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_notification_trialproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicate',
            name='interest_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
